Allow cancelling tasks/bundles
mrc-ide/didehpc pull request #109
Opened 2022-10-18 12:19 UTC by weshinsley

2022-10-18 15:44 UTC, richfitz requested changes

2022-10-18 17:14 UTC, weshinsley commented on tests/testthat/test-queue.R
> +
Yeah - bit messy, but I wanted to take advantage of the existing queuer_task object (t). `task_get_ids` is called only by `unsubmit`; I'm testing the inner bit here with a bogus pair of clones.

If I moved it I think I'd need to duplicate the submission machinery from the top of this test, to get a queuer_task object to play with.

2022-10-18 17:15 UTC, weshinsley commented on tests/testthat/test-queue.R
> +
(I could move 150-151 easily, as that's just testing multiple strings works

2022-11-23 20:19 UTC, weshinsley commented on tests/testthat/test-queue.R
> +
Try now... I've duplicated a little bit, but not too much

2022-11-23 20:43 UTC, weshinsley commented
I'm not sure why one of the ubuntu CI tests behaves so differently...

2022-11-24 13:25 UTC, richfitz approved these changes

2022-11-24 13:28 UTC, merged